// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Projeto001.Domain.Entities;

namespace Projeto001.Infraestrutura.Data;

public partial class Projeto001Context : DbContext
{
    public Projeto001Context(DbContextOptions<Projeto001Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Contato> Contatos { get; set; }

    public virtual DbSet<Endereco> Enderecos { get; set; }

    public virtual DbSet<Pessoa> Pessoas { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Contato>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Contatos__3214EC07B9263C0D");

            entity.Property(e => e.Conteudo)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.DataAlteracao).HasColumnType("datetime");
            entity.Property(e => e.DataCadastro).HasColumnType("datetime");
            entity.Property(e => e.IdPessoa).HasColumnName("Id_Pessoa");

            entity.HasOne(d => d.IdPessoaNavigation).WithMany(p => p.Contatos)
                .HasForeignKey(d => d.IdPessoa)
                .HasConstraintName("FK__Contatos__Usuari__3C69FB99");
        });

        modelBuilder.Entity<Endereco>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Endereco__3214EC07EF9AD242");

            entity.Property(e => e.Bairro)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Cep)
                .IsRequired()
                .HasMaxLength(9)
                .IsUnicode(false)
                .HasColumnName("CEP");
            entity.Property(e => e.Cidade)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DataAlteracao).HasColumnType("datetime");
            entity.Property(e => e.DataCadastro).HasColumnType("datetime");
            entity.Property(e => e.IdPessoa).HasColumnName("Id_Pessoa");
            entity.Property(e => e.Logradouro)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Numero)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Uf)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("UF");

            entity.HasOne(d => d.IdPessoaNavigation).WithMany(p => p.Enderecos)
                .HasForeignKey(d => d.IdPessoa)
                .HasConstraintName("FK__Enderecos__Usuar__398D8EEE");
        });

        modelBuilder.Entity<Pessoa>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Pessoas__3214EC0717E5A397");

            entity.Property(e => e.Cgc)
                .IsRequired()
                .HasMaxLength(18)
                .IsUnicode(false)
                .HasColumnName("CGC");
            entity.Property(e => e.DataAlteracao).HasColumnType("datetime");
            entity.Property(e => e.DataCadastro).HasColumnType("datetime");
            entity.Property(e => e.DataNascimento).HasColumnType("smalldatetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Genero)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Mae)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Pai)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Rg)
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("RG");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuarios__3214EC075B10E99B");

            entity.Property(e => e.AltSenha).HasColumnName("Alt_Senha");
            entity.Property(e => e.IdPessoa).HasColumnName("Id_Pessoa");
            entity.Property(e => e.Senha).IsUnicode(false);
            entity.Property(e => e.Username)
                .HasMaxLength(80)
                .IsUnicode(false);

            entity.HasOne(d => d.IdPessoaNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdPessoa)
                .HasConstraintName("FK__Usuarios__Id_Pes__3F466844");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}