// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto001.Domain.Entities;

public partial class Contato
{
    [Key]
    public int Id { get; set; }

    [StringLength(80)]
    [Unicode(false)]
    public string Conteudo { get; set; }

    public int? Tipo { get; set; }

    [Column("Id_Pessoa")]
    public int? IdPessoa { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }

    public int? UsuarioCadastro { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataAlteracao { get; set; }

    public int? UsuarioAlteracao { get; set; }

    [ForeignKey("IdPessoa")]
    [InverseProperty("Contatos")]
    public virtual Pessoa IdPessoaNavigation { get; set; }
}