// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto001.Domain.Entities;

public partial class Pessoa
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("CGC")]
    [StringLength(18)]
    [Unicode(false)]
    public string Cgc { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime DataNascimento { get; set; }

    [Column("RG")]
    [StringLength(11)]
    [Unicode(false)]
    public string Rg { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Genero { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Mae { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Pai { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }

    public int? UsuarioCadastro { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataAlteracao { get; set; }

    public int? UsuarioAlteracao { get; set; }

    [InverseProperty("IdPessoaNavigation")]
    public virtual ICollection<Contato> Contatos { get; set; } = new List<Contato>();

    [InverseProperty("IdPessoaNavigation")]
    public virtual ICollection<Endereco> Enderecos { get; set; } = new List<Endereco>();

    [InverseProperty("IdPessoaNavigation")]
    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}