// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto001.Domain.Entities;

public partial class Usuario
{
    private string _senha;
    private string _username;

    [Key]
    public int Id { get; set; }

    [StringLength(80)]
    [Unicode(false)]
    public string Username 
    {
        get => _username.ToUpper();
        set => _username = value; 
    }

    [Unicode(false)]
    public string Senha
    {
        get => _senha;
        set => _senha = Util.ComputeSha512Hash(value);
    }

    public int? Permissao { get; set; }

    [Column("Alt_Senha")]
    public bool? AltSenha { get; set; }

    [Column("Id_Pessoa")]
    public int? IdPessoa { get; set; }

    [ForeignKey("IdPessoa")]
    [InverseProperty("Usuarios")]
    public virtual Pessoa IdPessoaNavigation { get; set; }
}